# Generated by Django 3.2.10 on 2022-12-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_user_set', through='chat.Chat', to='chat.Group'),
        ),
    ]
