# Generated by Django 3.2.10 on 2022-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20221210_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('todo', models.ManyToManyField(to='todo.Todo')),
            ],
        ),
    ]
