# Generated by Django 3.2.10 on 2022-12-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='todo',
        ),
        migrations.AddField(
            model_name='tag',
            name='todos',
            field=models.ManyToManyField(related_name='tags', to='todo.Todo'),
        ),
    ]
